### ISSUE TITLE
Select play triggers / Select stop triggers Error not authorized to perform the requested operation

### ISSUE THREAD

**Issue by jameswiser** [SmartThingsUle/DLNA-PLAYER#3]
When "Select play triggers?" or "Select stop triggers?" is selected you get the error message below

Error message : You are not authorized to perform the requested operation

**Comment by SmartThingsUle** [comment]
Hi, it was a typo, now itsfixed try it

**Comment by jameswiser** [comment]
Yes it work now.  Thanks !

**Comment by jameswiser** [comment]
Thanks I tried it.  It works.  I closed the issue.  Great Program
